// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: cascadia/reward/v1/tx.proto

package types

import (
	context "context"
	fmt "fmt"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type MsgCreateRewardContract struct {
	Creator string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	Address string `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
}

func (m *MsgCreateRewardContract) Reset()         { *m = MsgCreateRewardContract{} }
func (m *MsgCreateRewardContract) String() string { return proto.CompactTextString(m) }
func (*MsgCreateRewardContract) ProtoMessage()    {}
func (*MsgCreateRewardContract) Descriptor() ([]byte, []int) {
	return fileDescriptor_b099be483d073bb6, []int{0}
}
func (m *MsgCreateRewardContract) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgCreateRewardContract) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgCreateRewardContract.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgCreateRewardContract) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCreateRewardContract.Merge(m, src)
}
func (m *MsgCreateRewardContract) XXX_Size() int {
	return m.Size()
}
func (m *MsgCreateRewardContract) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCreateRewardContract.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCreateRewardContract proto.InternalMessageInfo

func (m *MsgCreateRewardContract) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgCreateRewardContract) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type MsgCreateRewardContractResponse struct {
	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (m *MsgCreateRewardContractResponse) Reset()         { *m = MsgCreateRewardContractResponse{} }
func (m *MsgCreateRewardContractResponse) String() string { return proto.CompactTextString(m) }
func (*MsgCreateRewardContractResponse) ProtoMessage()    {}
func (*MsgCreateRewardContractResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b099be483d073bb6, []int{1}
}
func (m *MsgCreateRewardContractResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgCreateRewardContractResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgCreateRewardContractResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgCreateRewardContractResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCreateRewardContractResponse.Merge(m, src)
}
func (m *MsgCreateRewardContractResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgCreateRewardContractResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCreateRewardContractResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCreateRewardContractResponse proto.InternalMessageInfo

func (m *MsgCreateRewardContractResponse) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type MsgUpdateRewardContract struct {
	Creator string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	Id      uint64 `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	Address string `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
}

func (m *MsgUpdateRewardContract) Reset()         { *m = MsgUpdateRewardContract{} }
func (m *MsgUpdateRewardContract) String() string { return proto.CompactTextString(m) }
func (*MsgUpdateRewardContract) ProtoMessage()    {}
func (*MsgUpdateRewardContract) Descriptor() ([]byte, []int) {
	return fileDescriptor_b099be483d073bb6, []int{2}
}
func (m *MsgUpdateRewardContract) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdateRewardContract) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdateRewardContract.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdateRewardContract) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdateRewardContract.Merge(m, src)
}
func (m *MsgUpdateRewardContract) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdateRewardContract) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdateRewardContract.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdateRewardContract proto.InternalMessageInfo

func (m *MsgUpdateRewardContract) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgUpdateRewardContract) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *MsgUpdateRewardContract) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type MsgUpdateRewardContractResponse struct {
}

func (m *MsgUpdateRewardContractResponse) Reset()         { *m = MsgUpdateRewardContractResponse{} }
func (m *MsgUpdateRewardContractResponse) String() string { return proto.CompactTextString(m) }
func (*MsgUpdateRewardContractResponse) ProtoMessage()    {}
func (*MsgUpdateRewardContractResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b099be483d073bb6, []int{3}
}
func (m *MsgUpdateRewardContractResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdateRewardContractResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdateRewardContractResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdateRewardContractResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdateRewardContractResponse.Merge(m, src)
}
func (m *MsgUpdateRewardContractResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdateRewardContractResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdateRewardContractResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdateRewardContractResponse proto.InternalMessageInfo

type MsgDeleteRewardContract struct {
	Creator string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	Id      uint64 `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
}

func (m *MsgDeleteRewardContract) Reset()         { *m = MsgDeleteRewardContract{} }
func (m *MsgDeleteRewardContract) String() string { return proto.CompactTextString(m) }
func (*MsgDeleteRewardContract) ProtoMessage()    {}
func (*MsgDeleteRewardContract) Descriptor() ([]byte, []int) {
	return fileDescriptor_b099be483d073bb6, []int{4}
}
func (m *MsgDeleteRewardContract) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgDeleteRewardContract) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgDeleteRewardContract.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgDeleteRewardContract) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgDeleteRewardContract.Merge(m, src)
}
func (m *MsgDeleteRewardContract) XXX_Size() int {
	return m.Size()
}
func (m *MsgDeleteRewardContract) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgDeleteRewardContract.DiscardUnknown(m)
}

var xxx_messageInfo_MsgDeleteRewardContract proto.InternalMessageInfo

func (m *MsgDeleteRewardContract) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgDeleteRewardContract) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type MsgDeleteRewardContractResponse struct {
}

func (m *MsgDeleteRewardContractResponse) Reset()         { *m = MsgDeleteRewardContractResponse{} }
func (m *MsgDeleteRewardContractResponse) String() string { return proto.CompactTextString(m) }
func (*MsgDeleteRewardContractResponse) ProtoMessage()    {}
func (*MsgDeleteRewardContractResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b099be483d073bb6, []int{5}
}
func (m *MsgDeleteRewardContractResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgDeleteRewardContractResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgDeleteRewardContractResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgDeleteRewardContractResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgDeleteRewardContractResponse.Merge(m, src)
}
func (m *MsgDeleteRewardContractResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgDeleteRewardContractResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgDeleteRewardContractResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgDeleteRewardContractResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*MsgCreateRewardContract)(nil), "cascadia.reward.v1.MsgCreateRewardContract")
	proto.RegisterType((*MsgCreateRewardContractResponse)(nil), "cascadia.reward.v1.MsgCreateRewardContractResponse")
	proto.RegisterType((*MsgUpdateRewardContract)(nil), "cascadia.reward.v1.MsgUpdateRewardContract")
	proto.RegisterType((*MsgUpdateRewardContractResponse)(nil), "cascadia.reward.v1.MsgUpdateRewardContractResponse")
	proto.RegisterType((*MsgDeleteRewardContract)(nil), "cascadia.reward.v1.MsgDeleteRewardContract")
	proto.RegisterType((*MsgDeleteRewardContractResponse)(nil), "cascadia.reward.v1.MsgDeleteRewardContractResponse")
}

func init() { proto.RegisterFile("cascadia/reward/v1/tx.proto", fileDescriptor_b099be483d073bb6) }

var fileDescriptor_b099be483d073bb6 = []byte{
	// 332 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x93, 0xc1, 0x4a, 0xc3, 0x30,
	0x1c, 0xc6, 0xd7, 0x4e, 0x14, 0x73, 0xf0, 0x50, 0x06, 0x8e, 0x09, 0x51, 0x7b, 0x1a, 0x08, 0x29,
	0x73, 0xf8, 0x02, 0xce, 0x6b, 0x11, 0x0a, 0x5e, 0x04, 0x91, 0x2c, 0x89, 0xb5, 0xa0, 0x4d, 0x49,
	0xb2, 0x59, 0xdf, 0xc2, 0xc7, 0xf2, 0xb8, 0xa3, 0x47, 0x69, 0x1f, 0xc1, 0x17, 0x90, 0xa6, 0xcd,
	0x50, 0x4c, 0x06, 0xf3, 0xd6, 0xe4, 0xff, 0xe5, 0xfb, 0x7e, 0x7c, 0xe5, 0x0f, 0x8e, 0x08, 0x96,
	0x04, 0xd3, 0x0c, 0x47, 0x82, 0xbd, 0x60, 0x41, 0xa3, 0xe5, 0x24, 0x52, 0x25, 0x2a, 0x04, 0x57,
	0x3c, 0x08, 0xcc, 0x10, 0xb5, 0x43, 0xb4, 0x9c, 0x8c, 0xc6, 0x96, 0x07, 0xed, 0xd7, 0x3d, 0xe1,
	0xb9, 0x12, 0x98, 0xa8, 0xf6, 0x75, 0x18, 0x83, 0xc3, 0x58, 0xa6, 0x33, 0xc1, 0xb0, 0x62, 0x89,
	0x56, 0xcc, 0x3a, 0x41, 0x30, 0x04, 0x7b, 0xa4, 0xb9, 0xe7, 0x62, 0xe8, 0x9d, 0x78, 0xe3, 0xfd,
	0xc4, 0x1c, 0x9b, 0x09, 0xa6, 0x54, 0x30, 0x29, 0x87, 0x7e, 0x3b, 0xe9, 0x8e, 0xe1, 0x04, 0x1c,
	0x3b, 0xec, 0x12, 0x26, 0x0b, 0x9e, 0x4b, 0x16, 0x1c, 0x00, 0x3f, 0xa3, 0xda, 0x71, 0x27, 0xf1,
	0x33, 0x1a, 0xde, 0x69, 0x82, 0x9b, 0x82, 0x6e, 0x43, 0xd0, 0x9a, 0xf8, 0xc6, 0xe4, 0x27, 0x51,
	0xff, 0x37, 0xd1, 0xa9, 0x26, 0xb2, 0xd9, 0x1b, 0xa2, 0x70, 0xa6, 0x09, 0xae, 0xd8, 0x13, 0xfb,
	0x3f, 0x41, 0x97, 0x63, 0x33, 0x31, 0x39, 0xe7, 0x5f, 0x3e, 0xe8, 0xc7, 0x32, 0x0d, 0x4a, 0x30,
	0xb0, 0x16, 0x7e, 0x86, 0xfe, 0xfe, 0x4a, 0xe4, 0xa8, 0x73, 0x34, 0xdd, 0x42, 0xbc, 0xee, 0xbe,
	0x04, 0x03, 0x6b, 0xd1, 0xae, 0x64, 0x9b, 0xd8, 0x99, 0xbc, 0xa9, 0xe3, 0x26, 0xd9, 0x5a, 0xb0,
	0x2b, 0xd9, 0x26, 0x76, 0x26, 0x6f, 0x6a, 0xfd, 0xf2, 0xfa, 0xbd, 0x82, 0xde, 0xaa, 0x82, 0xde,
	0x67, 0x05, 0xbd, 0xb7, 0x1a, 0xf6, 0x56, 0x35, 0xec, 0x7d, 0xd4, 0xb0, 0x77, 0x7b, 0x91, 0x66,
	0xea, 0x71, 0x31, 0x47, 0x84, 0x3f, 0x47, 0xc6, 0xf8, 0x81, 0x2f, 0x72, 0x8a, 0x55, 0xc6, 0xf3,
	0xf5, 0x55, 0x54, 0x9a, 0x2d, 0x52, 0xaf, 0x05, 0x93, 0xf3, 0x5d, 0xbd, 0x39, 0xd3, 0xef, 0x00,
	0x00, 0x00, 0xff, 0xff, 0x68, 0xac, 0x80, 0x56, 0x96, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	CreateRewardContract(ctx context.Context, in *MsgCreateRewardContract, opts ...grpc.CallOption) (*MsgCreateRewardContractResponse, error)
	UpdateRewardContract(ctx context.Context, in *MsgUpdateRewardContract, opts ...grpc.CallOption) (*MsgUpdateRewardContractResponse, error)
	DeleteRewardContract(ctx context.Context, in *MsgDeleteRewardContract, opts ...grpc.CallOption) (*MsgDeleteRewardContractResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) CreateRewardContract(ctx context.Context, in *MsgCreateRewardContract, opts ...grpc.CallOption) (*MsgCreateRewardContractResponse, error) {
	out := new(MsgCreateRewardContractResponse)
	err := c.cc.Invoke(ctx, "/cascadia.reward.v1.Msg/CreateRewardContract", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) UpdateRewardContract(ctx context.Context, in *MsgUpdateRewardContract, opts ...grpc.CallOption) (*MsgUpdateRewardContractResponse, error) {
	out := new(MsgUpdateRewardContractResponse)
	err := c.cc.Invoke(ctx, "/cascadia.reward.v1.Msg/UpdateRewardContract", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) DeleteRewardContract(ctx context.Context, in *MsgDeleteRewardContract, opts ...grpc.CallOption) (*MsgDeleteRewardContractResponse, error) {
	out := new(MsgDeleteRewardContractResponse)
	err := c.cc.Invoke(ctx, "/cascadia.reward.v1.Msg/DeleteRewardContract", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	CreateRewardContract(context.Context, *MsgCreateRewardContract) (*MsgCreateRewardContractResponse, error)
	UpdateRewardContract(context.Context, *MsgUpdateRewardContract) (*MsgUpdateRewardContractResponse, error)
	DeleteRewardContract(context.Context, *MsgDeleteRewardContract) (*MsgDeleteRewardContractResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) CreateRewardContract(ctx context.Context, req *MsgCreateRewardContract) (*MsgCreateRewardContractResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateRewardContract not implemented")
}
func (*UnimplementedMsgServer) UpdateRewardContract(ctx context.Context, req *MsgUpdateRewardContract) (*MsgUpdateRewardContractResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateRewardContract not implemented")
}
func (*UnimplementedMsgServer) DeleteRewardContract(ctx context.Context, req *MsgDeleteRewardContract) (*MsgDeleteRewardContractResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteRewardContract not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_CreateRewardContract_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgCreateRewardContract)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).CreateRewardContract(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cascadia.reward.v1.Msg/CreateRewardContract",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).CreateRewardContract(ctx, req.(*MsgCreateRewardContract))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_UpdateRewardContract_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgUpdateRewardContract)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).UpdateRewardContract(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cascadia.reward.v1.Msg/UpdateRewardContract",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).UpdateRewardContract(ctx, req.(*MsgUpdateRewardContract))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_DeleteRewardContract_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgDeleteRewardContract)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).DeleteRewardContract(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cascadia.reward.v1.Msg/DeleteRewardContract",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).DeleteRewardContract(ctx, req.(*MsgDeleteRewardContract))
	}
	return interceptor(ctx, in, info, handler)
}

var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "cascadia.reward.v1.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateRewardContract",
			Handler:    _Msg_CreateRewardContract_Handler,
		},
		{
			MethodName: "UpdateRewardContract",
			Handler:    _Msg_UpdateRewardContract_Handler,
		},
		{
			MethodName: "DeleteRewardContract",
			Handler:    _Msg_DeleteRewardContract_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cascadia/reward/v1/tx.proto",
}

func (m *MsgCreateRewardContract) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgCreateRewardContract) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgCreateRewardContract) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgCreateRewardContractResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgCreateRewardContractResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgCreateRewardContractResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Id != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *MsgUpdateRewardContract) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdateRewardContract) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdateRewardContract) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0x1a
	}
	if m.Id != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgUpdateRewardContractResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdateRewardContractResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdateRewardContractResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgDeleteRewardContract) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgDeleteRewardContract) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgDeleteRewardContract) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Id != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgDeleteRewardContractResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgDeleteRewardContractResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgDeleteRewardContractResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgCreateRewardContract) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgCreateRewardContractResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovTx(uint64(m.Id))
	}
	return n
}

func (m *MsgUpdateRewardContract) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.Id != 0 {
		n += 1 + sovTx(uint64(m.Id))
	}
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgUpdateRewardContractResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgDeleteRewardContract) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.Id != 0 {
		n += 1 + sovTx(uint64(m.Id))
	}
	return n
}

func (m *MsgDeleteRewardContractResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgCreateRewardContract) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgCreateRewardContract: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgCreateRewardContract: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgCreateRewardContractResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgCreateRewardContractResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgCreateRewardContractResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgUpdateRewardContract) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdateRewardContract: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdateRewardContract: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgUpdateRewardContractResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdateRewardContractResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdateRewardContractResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgDeleteRewardContract) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgDeleteRewardContract: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgDeleteRewardContract: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgDeleteRewardContractResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgDeleteRewardContractResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgDeleteRewardContractResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
