// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: cascadia/oracle/v1/tx.proto

package types

import (
	context "context"
	fmt "fmt"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type MsgRequestBandPrice struct {
	Creator        string                                   `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	OracleScriptID uint64                                   `protobuf:"varint,2,opt,name=oracle_script_id,json=oracleScriptId,proto3" json:"oracle_script_id,omitempty" yaml:"oracle_script_id"`
	SourceChannel  string                                   `protobuf:"bytes,3,opt,name=source_channel,json=sourceChannel,proto3" json:"source_channel,omitempty"`
	Calldata       *BandPriceCallData                       `protobuf:"bytes,4,opt,name=calldata,proto3" json:"calldata,omitempty"`
	AskCount       uint64                                   `protobuf:"varint,5,opt,name=ask_count,json=askCount,proto3" json:"ask_count,omitempty"`
	MinCount       uint64                                   `protobuf:"varint,6,opt,name=min_count,json=minCount,proto3" json:"min_count,omitempty"`
	FeeLimit       github_com_cosmos_cosmos_sdk_types.Coins `protobuf:"bytes,7,rep,name=fee_limit,json=feeLimit,proto3,castrepeated=github.com/cosmos/cosmos-sdk/types.Coins" json:"fee_limit"`
	PrepareGas     uint64                                   `protobuf:"varint,8,opt,name=prepare_gas,json=prepareGas,proto3" json:"prepare_gas,omitempty"`
	ExecuteGas     uint64                                   `protobuf:"varint,9,opt,name=execute_gas,json=executeGas,proto3" json:"execute_gas,omitempty"`
	ClientID       string                                   `protobuf:"bytes,10,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
}

func (m *MsgRequestBandPrice) Reset()         { *m = MsgRequestBandPrice{} }
func (m *MsgRequestBandPrice) String() string { return proto.CompactTextString(m) }
func (*MsgRequestBandPrice) ProtoMessage()    {}
func (*MsgRequestBandPrice) Descriptor() ([]byte, []int) {
	return fileDescriptor_1bc8159a83dc2a85, []int{0}
}
func (m *MsgRequestBandPrice) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgRequestBandPrice) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgRequestBandPrice.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgRequestBandPrice) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgRequestBandPrice.Merge(m, src)
}
func (m *MsgRequestBandPrice) XXX_Size() int {
	return m.Size()
}
func (m *MsgRequestBandPrice) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgRequestBandPrice.DiscardUnknown(m)
}

var xxx_messageInfo_MsgRequestBandPrice proto.InternalMessageInfo

func (m *MsgRequestBandPrice) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgRequestBandPrice) GetOracleScriptID() uint64 {
	if m != nil {
		return m.OracleScriptID
	}
	return 0
}

func (m *MsgRequestBandPrice) GetSourceChannel() string {
	if m != nil {
		return m.SourceChannel
	}
	return ""
}

func (m *MsgRequestBandPrice) GetCalldata() *BandPriceCallData {
	if m != nil {
		return m.Calldata
	}
	return nil
}

func (m *MsgRequestBandPrice) GetAskCount() uint64 {
	if m != nil {
		return m.AskCount
	}
	return 0
}

func (m *MsgRequestBandPrice) GetMinCount() uint64 {
	if m != nil {
		return m.MinCount
	}
	return 0
}

func (m *MsgRequestBandPrice) GetFeeLimit() github_com_cosmos_cosmos_sdk_types.Coins {
	if m != nil {
		return m.FeeLimit
	}
	return nil
}

func (m *MsgRequestBandPrice) GetPrepareGas() uint64 {
	if m != nil {
		return m.PrepareGas
	}
	return 0
}

func (m *MsgRequestBandPrice) GetExecuteGas() uint64 {
	if m != nil {
		return m.ExecuteGas
	}
	return 0
}

func (m *MsgRequestBandPrice) GetClientID() string {
	if m != nil {
		return m.ClientID
	}
	return ""
}

type MsgRequestBandPriceResponse struct {
}

func (m *MsgRequestBandPriceResponse) Reset()         { *m = MsgRequestBandPriceResponse{} }
func (m *MsgRequestBandPriceResponse) String() string { return proto.CompactTextString(m) }
func (*MsgRequestBandPriceResponse) ProtoMessage()    {}
func (*MsgRequestBandPriceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1bc8159a83dc2a85, []int{1}
}
func (m *MsgRequestBandPriceResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgRequestBandPriceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgRequestBandPriceResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgRequestBandPriceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgRequestBandPriceResponse.Merge(m, src)
}
func (m *MsgRequestBandPriceResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgRequestBandPriceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgRequestBandPriceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgRequestBandPriceResponse proto.InternalMessageInfo

type MsgFeedPrice struct {
	Asset    string                                 `protobuf:"bytes,1,opt,name=asset,proto3" json:"asset,omitempty"`
	Price    github_com_cosmos_cosmos_sdk_types.Dec `protobuf:"bytes,2,opt,name=price,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Dec" json:"price"`
	Source   string                                 `protobuf:"bytes,3,opt,name=source,proto3" json:"source,omitempty"`
	Provider string                                 `protobuf:"bytes,4,opt,name=provider,proto3" json:"provider,omitempty"`
}

func (m *MsgFeedPrice) Reset()         { *m = MsgFeedPrice{} }
func (m *MsgFeedPrice) String() string { return proto.CompactTextString(m) }
func (*MsgFeedPrice) ProtoMessage()    {}
func (*MsgFeedPrice) Descriptor() ([]byte, []int) {
	return fileDescriptor_1bc8159a83dc2a85, []int{2}
}
func (m *MsgFeedPrice) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgFeedPrice) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgFeedPrice.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgFeedPrice) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgFeedPrice.Merge(m, src)
}
func (m *MsgFeedPrice) XXX_Size() int {
	return m.Size()
}
func (m *MsgFeedPrice) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgFeedPrice.DiscardUnknown(m)
}

var xxx_messageInfo_MsgFeedPrice proto.InternalMessageInfo

func (m *MsgFeedPrice) GetAsset() string {
	if m != nil {
		return m.Asset
	}
	return ""
}

func (m *MsgFeedPrice) GetSource() string {
	if m != nil {
		return m.Source
	}
	return ""
}

func (m *MsgFeedPrice) GetProvider() string {
	if m != nil {
		return m.Provider
	}
	return ""
}

type MsgFeedPriceResponse struct {
}

func (m *MsgFeedPriceResponse) Reset()         { *m = MsgFeedPriceResponse{} }
func (m *MsgFeedPriceResponse) String() string { return proto.CompactTextString(m) }
func (*MsgFeedPriceResponse) ProtoMessage()    {}
func (*MsgFeedPriceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1bc8159a83dc2a85, []int{3}
}
func (m *MsgFeedPriceResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgFeedPriceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgFeedPriceResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgFeedPriceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgFeedPriceResponse.Merge(m, src)
}
func (m *MsgFeedPriceResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgFeedPriceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgFeedPriceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgFeedPriceResponse proto.InternalMessageInfo

type MsgSetPriceFeeder struct {
	Feeder   string `protobuf:"bytes,1,opt,name=feeder,proto3" json:"feeder,omitempty"`
	IsActive bool   `protobuf:"varint,2,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
}

func (m *MsgSetPriceFeeder) Reset()         { *m = MsgSetPriceFeeder{} }
func (m *MsgSetPriceFeeder) String() string { return proto.CompactTextString(m) }
func (*MsgSetPriceFeeder) ProtoMessage()    {}
func (*MsgSetPriceFeeder) Descriptor() ([]byte, []int) {
	return fileDescriptor_1bc8159a83dc2a85, []int{4}
}
func (m *MsgSetPriceFeeder) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgSetPriceFeeder) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgSetPriceFeeder.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgSetPriceFeeder) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgSetPriceFeeder.Merge(m, src)
}
func (m *MsgSetPriceFeeder) XXX_Size() int {
	return m.Size()
}
func (m *MsgSetPriceFeeder) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgSetPriceFeeder.DiscardUnknown(m)
}

var xxx_messageInfo_MsgSetPriceFeeder proto.InternalMessageInfo

func (m *MsgSetPriceFeeder) GetFeeder() string {
	if m != nil {
		return m.Feeder
	}
	return ""
}

func (m *MsgSetPriceFeeder) GetIsActive() bool {
	if m != nil {
		return m.IsActive
	}
	return false
}

type MsgSetPriceFeederResponse struct {
}

func (m *MsgSetPriceFeederResponse) Reset()         { *m = MsgSetPriceFeederResponse{} }
func (m *MsgSetPriceFeederResponse) String() string { return proto.CompactTextString(m) }
func (*MsgSetPriceFeederResponse) ProtoMessage()    {}
func (*MsgSetPriceFeederResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1bc8159a83dc2a85, []int{5}
}
func (m *MsgSetPriceFeederResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgSetPriceFeederResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgSetPriceFeederResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgSetPriceFeederResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgSetPriceFeederResponse.Merge(m, src)
}
func (m *MsgSetPriceFeederResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgSetPriceFeederResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgSetPriceFeederResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgSetPriceFeederResponse proto.InternalMessageInfo

type MsgDeletePriceFeeder struct {
	Feeder string `protobuf:"bytes,1,opt,name=feeder,proto3" json:"feeder,omitempty"`
}

func (m *MsgDeletePriceFeeder) Reset()         { *m = MsgDeletePriceFeeder{} }
func (m *MsgDeletePriceFeeder) String() string { return proto.CompactTextString(m) }
func (*MsgDeletePriceFeeder) ProtoMessage()    {}
func (*MsgDeletePriceFeeder) Descriptor() ([]byte, []int) {
	return fileDescriptor_1bc8159a83dc2a85, []int{6}
}
func (m *MsgDeletePriceFeeder) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgDeletePriceFeeder) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgDeletePriceFeeder.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgDeletePriceFeeder) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgDeletePriceFeeder.Merge(m, src)
}
func (m *MsgDeletePriceFeeder) XXX_Size() int {
	return m.Size()
}
func (m *MsgDeletePriceFeeder) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgDeletePriceFeeder.DiscardUnknown(m)
}

var xxx_messageInfo_MsgDeletePriceFeeder proto.InternalMessageInfo

func (m *MsgDeletePriceFeeder) GetFeeder() string {
	if m != nil {
		return m.Feeder
	}
	return ""
}

type MsgDeletePriceFeederResponse struct {
}

func (m *MsgDeletePriceFeederResponse) Reset()         { *m = MsgDeletePriceFeederResponse{} }
func (m *MsgDeletePriceFeederResponse) String() string { return proto.CompactTextString(m) }
func (*MsgDeletePriceFeederResponse) ProtoMessage()    {}
func (*MsgDeletePriceFeederResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1bc8159a83dc2a85, []int{7}
}
func (m *MsgDeletePriceFeederResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgDeletePriceFeederResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgDeletePriceFeederResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgDeletePriceFeederResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgDeletePriceFeederResponse.Merge(m, src)
}
func (m *MsgDeletePriceFeederResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgDeletePriceFeederResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgDeletePriceFeederResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgDeletePriceFeederResponse proto.InternalMessageInfo

type MsgFeedMultiplePrices struct {
	Creator string  `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	Prices  []Price `protobuf:"bytes,2,rep,name=prices,proto3" json:"prices"`
}

func (m *MsgFeedMultiplePrices) Reset()         { *m = MsgFeedMultiplePrices{} }
func (m *MsgFeedMultiplePrices) String() string { return proto.CompactTextString(m) }
func (*MsgFeedMultiplePrices) ProtoMessage()    {}
func (*MsgFeedMultiplePrices) Descriptor() ([]byte, []int) {
	return fileDescriptor_1bc8159a83dc2a85, []int{8}
}
func (m *MsgFeedMultiplePrices) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgFeedMultiplePrices) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgFeedMultiplePrices.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgFeedMultiplePrices) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgFeedMultiplePrices.Merge(m, src)
}
func (m *MsgFeedMultiplePrices) XXX_Size() int {
	return m.Size()
}
func (m *MsgFeedMultiplePrices) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgFeedMultiplePrices.DiscardUnknown(m)
}

var xxx_messageInfo_MsgFeedMultiplePrices proto.InternalMessageInfo

func (m *MsgFeedMultiplePrices) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgFeedMultiplePrices) GetPrices() []Price {
	if m != nil {
		return m.Prices
	}
	return nil
}

type MsgFeedMultiplePricesResponse struct {
}

func (m *MsgFeedMultiplePricesResponse) Reset()         { *m = MsgFeedMultiplePricesResponse{} }
func (m *MsgFeedMultiplePricesResponse) String() string { return proto.CompactTextString(m) }
func (*MsgFeedMultiplePricesResponse) ProtoMessage()    {}
func (*MsgFeedMultiplePricesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1bc8159a83dc2a85, []int{9}
}
func (m *MsgFeedMultiplePricesResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgFeedMultiplePricesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgFeedMultiplePricesResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgFeedMultiplePricesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgFeedMultiplePricesResponse.Merge(m, src)
}
func (m *MsgFeedMultiplePricesResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgFeedMultiplePricesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgFeedMultiplePricesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgFeedMultiplePricesResponse proto.InternalMessageInfo

type MsgUpdateChannel struct {
	Creator string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	Channel string `protobuf:"bytes,2,opt,name=channel,proto3" json:"channel,omitempty"`
}

func (m *MsgUpdateChannel) Reset()         { *m = MsgUpdateChannel{} }
func (m *MsgUpdateChannel) String() string { return proto.CompactTextString(m) }
func (*MsgUpdateChannel) ProtoMessage()    {}
func (*MsgUpdateChannel) Descriptor() ([]byte, []int) {
	return fileDescriptor_1bc8159a83dc2a85, []int{10}
}
func (m *MsgUpdateChannel) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdateChannel) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdateChannel.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdateChannel) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdateChannel.Merge(m, src)
}
func (m *MsgUpdateChannel) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdateChannel) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdateChannel.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdateChannel proto.InternalMessageInfo

func (m *MsgUpdateChannel) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgUpdateChannel) GetChannel() string {
	if m != nil {
		return m.Channel
	}
	return ""
}

type MsgUpdateChannelResponse struct {
}

func (m *MsgUpdateChannelResponse) Reset()         { *m = MsgUpdateChannelResponse{} }
func (m *MsgUpdateChannelResponse) String() string { return proto.CompactTextString(m) }
func (*MsgUpdateChannelResponse) ProtoMessage()    {}
func (*MsgUpdateChannelResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1bc8159a83dc2a85, []int{11}
}
func (m *MsgUpdateChannelResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdateChannelResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdateChannelResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdateChannelResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdateChannelResponse.Merge(m, src)
}
func (m *MsgUpdateChannelResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdateChannelResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdateChannelResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdateChannelResponse proto.InternalMessageInfo

type MsgUpdatePriceStatistics struct {
	Creator string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	P360    string `protobuf:"bytes,2,opt,name=p360,proto3" json:"p360,omitempty"`
	P180    string `protobuf:"bytes,3,opt,name=p180,proto3" json:"p180,omitempty"`
	P90     string `protobuf:"bytes,4,opt,name=p90,proto3" json:"p90,omitempty"`
	P30     string `protobuf:"bytes,5,opt,name=p30,proto3" json:"p30,omitempty"`
	P14     string `protobuf:"bytes,6,opt,name=p14,proto3" json:"p14,omitempty"`
	P7      string `protobuf:"bytes,7,opt,name=p7,proto3" json:"p7,omitempty"`
	P1      string `protobuf:"bytes,8,opt,name=p1,proto3" json:"p1,omitempty"`
}

func (m *MsgUpdatePriceStatistics) Reset()         { *m = MsgUpdatePriceStatistics{} }
func (m *MsgUpdatePriceStatistics) String() string { return proto.CompactTextString(m) }
func (*MsgUpdatePriceStatistics) ProtoMessage()    {}
func (*MsgUpdatePriceStatistics) Descriptor() ([]byte, []int) {
	return fileDescriptor_1bc8159a83dc2a85, []int{12}
}
func (m *MsgUpdatePriceStatistics) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdatePriceStatistics) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdatePriceStatistics.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdatePriceStatistics) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdatePriceStatistics.Merge(m, src)
}
func (m *MsgUpdatePriceStatistics) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdatePriceStatistics) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdatePriceStatistics.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdatePriceStatistics proto.InternalMessageInfo

func (m *MsgUpdatePriceStatistics) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgUpdatePriceStatistics) GetP360() string {
	if m != nil {
		return m.P360
	}
	return ""
}

func (m *MsgUpdatePriceStatistics) GetP180() string {
	if m != nil {
		return m.P180
	}
	return ""
}

func (m *MsgUpdatePriceStatistics) GetP90() string {
	if m != nil {
		return m.P90
	}
	return ""
}

func (m *MsgUpdatePriceStatistics) GetP30() string {
	if m != nil {
		return m.P30
	}
	return ""
}

func (m *MsgUpdatePriceStatistics) GetP14() string {
	if m != nil {
		return m.P14
	}
	return ""
}

func (m *MsgUpdatePriceStatistics) GetP7() string {
	if m != nil {
		return m.P7
	}
	return ""
}

func (m *MsgUpdatePriceStatistics) GetP1() string {
	if m != nil {
		return m.P1
	}
	return ""
}

type MsgUpdatePriceStatisticsResponse struct {
}

func (m *MsgUpdatePriceStatisticsResponse) Reset()         { *m = MsgUpdatePriceStatisticsResponse{} }
func (m *MsgUpdatePriceStatisticsResponse) String() string { return proto.CompactTextString(m) }
func (*MsgUpdatePriceStatisticsResponse) ProtoMessage()    {}
func (*MsgUpdatePriceStatisticsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1bc8159a83dc2a85, []int{13}
}
func (m *MsgUpdatePriceStatisticsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdatePriceStatisticsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdatePriceStatisticsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdatePriceStatisticsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdatePriceStatisticsResponse.Merge(m, src)
}
func (m *MsgUpdatePriceStatisticsResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdatePriceStatisticsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdatePriceStatisticsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdatePriceStatisticsResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*MsgRequestBandPrice)(nil), "cascadia.oracle.v1.MsgRequestBandPrice")
	proto.RegisterType((*MsgRequestBandPriceResponse)(nil), "cascadia.oracle.v1.MsgRequestBandPriceResponse")
	proto.RegisterType((*MsgFeedPrice)(nil), "cascadia.oracle.v1.MsgFeedPrice")
	proto.RegisterType((*MsgFeedPriceResponse)(nil), "cascadia.oracle.v1.MsgFeedPriceResponse")
	proto.RegisterType((*MsgSetPriceFeeder)(nil), "cascadia.oracle.v1.MsgSetPriceFeeder")
	proto.RegisterType((*MsgSetPriceFeederResponse)(nil), "cascadia.oracle.v1.MsgSetPriceFeederResponse")
	proto.RegisterType((*MsgDeletePriceFeeder)(nil), "cascadia.oracle.v1.MsgDeletePriceFeeder")
	proto.RegisterType((*MsgDeletePriceFeederResponse)(nil), "cascadia.oracle.v1.MsgDeletePriceFeederResponse")
	proto.RegisterType((*MsgFeedMultiplePrices)(nil), "cascadia.oracle.v1.MsgFeedMultiplePrices")
	proto.RegisterType((*MsgFeedMultiplePricesResponse)(nil), "cascadia.oracle.v1.MsgFeedMultiplePricesResponse")
	proto.RegisterType((*MsgUpdateChannel)(nil), "cascadia.oracle.v1.MsgUpdateChannel")
	proto.RegisterType((*MsgUpdateChannelResponse)(nil), "cascadia.oracle.v1.MsgUpdateChannelResponse")
	proto.RegisterType((*MsgUpdatePriceStatistics)(nil), "cascadia.oracle.v1.MsgUpdatePriceStatistics")
	proto.RegisterType((*MsgUpdatePriceStatisticsResponse)(nil), "cascadia.oracle.v1.MsgUpdatePriceStatisticsResponse")
}

func init() { proto.RegisterFile("cascadia/oracle/v1/tx.proto", fileDescriptor_1bc8159a83dc2a85) }

var fileDescriptor_1bc8159a83dc2a85 = []byte{
	// 961 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x56, 0xcd, 0x6e, 0x23, 0x45,
	0x10, 0x8e, 0xf3, 0xb7, 0x76, 0x65, 0xd7, 0xca, 0x0e, 0xd9, 0x65, 0x76, 0xc2, 0xda, 0xd6, 0x40,
	0xc0, 0x2b, 0x91, 0x19, 0x3b, 0x09, 0x04, 0xb8, 0xad, 0x6d, 0x05, 0x22, 0x61, 0x2d, 0x9a, 0x08,
	0xad, 0xc4, 0x65, 0xd4, 0x9e, 0x69, 0x3b, 0x4d, 0xc6, 0xd3, 0xc3, 0x74, 0x3b, 0xca, 0x8a, 0x23,
	0x2f, 0xc0, 0x13, 0xf0, 0x00, 0x1c, 0x79, 0x8a, 0x3d, 0xee, 0x11, 0x71, 0x30, 0xc8, 0x79, 0x03,
	0xae, 0x5c, 0x50, 0xff, 0x78, 0xd6, 0xf1, 0x1f, 0xe6, 0xe4, 0xae, 0xfa, 0xbe, 0xae, 0xaf, 0xca,
	0x55, 0xa5, 0x1e, 0xd8, 0x0f, 0x10, 0x0b, 0x50, 0x48, 0x90, 0x4b, 0x53, 0x14, 0x44, 0xd8, 0xbd,
	0xae, 0xbb, 0xfc, 0xc6, 0x49, 0x52, 0xca, 0xa9, 0x61, 0x8c, 0x41, 0x47, 0x81, 0xce, 0x75, 0xdd,
	0xda, 0xeb, 0xd1, 0x1e, 0x95, 0xb0, 0x2b, 0x4e, 0x8a, 0x69, 0x95, 0x02, 0xca, 0xfa, 0x94, 0xb9,
	0x1d, 0xc4, 0x44, 0x88, 0x0e, 0xe6, 0xa8, 0xee, 0x06, 0x94, 0xc4, 0x1a, 0x7f, 0x7f, 0x8e, 0x4c,
	0x07, 0xc5, 0xa1, 0x9f, 0xa4, 0x24, 0xc0, 0x4b, 0x48, 0x88, 0x31, 0xcc, 0x7d, 0x12, 0x77, 0xdf,
	0x2a, 0xcd, 0x92, 0x26, 0x83, 0x1c, 0x2c, 0xc2, 0xfd, 0x2e, 0xc6, 0x21, 0x4e, 0x15, 0xcd, 0xfe,
	0x69, 0x13, 0xde, 0x69, 0xb3, 0x9e, 0x87, 0x7f, 0x18, 0x60, 0xc6, 0x1b, 0x28, 0x0e, 0xbf, 0x11,
	0x24, 0xc3, 0x84, 0x7b, 0x41, 0x8a, 0x11, 0xa7, 0xa9, 0x99, 0xab, 0xe4, 0xaa, 0x05, 0x6f, 0x6c,
	0x1a, 0x2f, 0x61, 0x57, 0x45, 0xf4, 0x59, 0x90, 0x92, 0x84, 0xfb, 0x24, 0x34, 0xd7, 0x2b, 0xb9,
	0xea, 0x66, 0xe3, 0x70, 0x34, 0x2c, 0x17, 0x5f, 0x48, 0xec, 0x42, 0x42, 0xe7, 0xad, 0xbf, 0x87,
	0xe5, 0x77, 0x5f, 0xa1, 0x7e, 0xf4, 0x85, 0x3d, 0x7d, 0xc7, 0xf6, 0x8a, 0x74, 0x92, 0x1a, 0x1a,
	0x07, 0x50, 0x64, 0x74, 0x90, 0x06, 0xd8, 0x0f, 0x2e, 0x51, 0x1c, 0xe3, 0xc8, 0xdc, 0x90, 0xca,
	0x0f, 0x94, 0xb7, 0xa9, 0x9c, 0xc6, 0x73, 0xc8, 0x07, 0x28, 0x8a, 0x42, 0xc4, 0x91, 0xb9, 0x59,
	0xc9, 0x55, 0x77, 0x8e, 0x0e, 0x9c, 0xd9, 0xfe, 0x38, 0x59, 0x29, 0x4d, 0x14, 0x45, 0x2d, 0xc4,
	0x91, 0x97, 0x5d, 0x33, 0xf6, 0xa1, 0x80, 0xd8, 0x95, 0x1f, 0xd0, 0x41, 0xcc, 0xcd, 0x2d, 0x91,
	0xbb, 0x97, 0x47, 0xec, 0xaa, 0x29, 0x6c, 0x01, 0xf6, 0x49, 0xac, 0xc1, 0x6d, 0x05, 0xf6, 0x49,
	0xac, 0xc0, 0x4b, 0x28, 0x74, 0x31, 0xf6, 0x23, 0xd2, 0x27, 0xdc, 0xbc, 0x57, 0xd9, 0xa8, 0xee,
	0x1c, 0x3d, 0x71, 0x54, 0xcf, 0x1d, 0xd1, 0x73, 0x47, 0xf7, 0xdc, 0x69, 0x52, 0x12, 0x37, 0x6a,
	0xaf, 0x87, 0xe5, 0xb5, 0x5f, 0xff, 0x2c, 0x57, 0x7b, 0x84, 0x5f, 0x0e, 0x3a, 0x4e, 0x40, 0xfb,
	0xae, 0x1e, 0x10, 0xf5, 0x73, 0xc8, 0xc2, 0x2b, 0x97, 0xbf, 0x4a, 0x30, 0x93, 0x17, 0x98, 0x97,
	0xef, 0x62, 0xfc, 0xb5, 0x08, 0x6e, 0x94, 0x61, 0x27, 0x49, 0x71, 0x82, 0x52, 0xec, 0xf7, 0x10,
	0x33, 0xf3, 0x32, 0x11, 0xd0, 0xae, 0x2f, 0x11, 0x13, 0x04, 0x7c, 0x83, 0x83, 0x01, 0x57, 0x84,
	0x82, 0x22, 0x68, 0x97, 0x20, 0x3c, 0x83, 0x42, 0x10, 0x11, 0x1c, 0xcb, 0x0e, 0x81, 0xf8, 0x2b,
	0x1b, 0xf7, 0x47, 0xc3, 0x72, 0xbe, 0x29, 0x9d, 0xe7, 0x2d, 0x2f, 0xaf, 0xe0, 0xf3, 0xd0, 0x7e,
	0x0a, 0xfb, 0x73, 0x86, 0xc0, 0xc3, 0x2c, 0xa1, 0x31, 0xc3, 0xf6, 0x2f, 0x39, 0xb8, 0xdf, 0x66,
	0xbd, 0x33, 0x8c, 0xf5, 0x74, 0xec, 0xc1, 0x96, 0x1c, 0x48, 0x3d, 0x1b, 0xca, 0x30, 0x5a, 0xb0,
	0x25, 0x27, 0x4c, 0x8e, 0x43, 0xa1, 0xe1, 0x88, 0xea, 0xff, 0x18, 0x96, 0x3f, 0x5c, 0xa1, 0xfa,
	0x16, 0x0e, 0x3c, 0x75, 0xd9, 0x78, 0x0c, 0xdb, 0xaa, 0xe1, 0xba, 0xfd, 0xda, 0x32, 0x2c, 0xc8,
	0x27, 0x29, 0xbd, 0x26, 0x21, 0x4e, 0x65, 0xdf, 0x0b, 0x5e, 0x66, 0xdb, 0x8f, 0x61, 0x6f, 0x32,
	0xbf, 0x2c, 0xf1, 0xaf, 0xe0, 0x61, 0x9b, 0xf5, 0x2e, 0x30, 0x97, 0xee, 0x33, 0x39, 0xf8, 0x42,
	0x40, 0xad, 0x80, 0xce, 0x5e, 0x5b, 0xa2, 0xf1, 0x84, 0xf9, 0x28, 0xe0, 0xe4, 0x5a, 0x95, 0x90,
	0xf7, 0xf2, 0x84, 0x3d, 0x97, 0xb6, 0xbd, 0x0f, 0x4f, 0x66, 0x22, 0x65, 0x32, 0x8e, 0x94, 0x6f,
	0xe1, 0x08, 0x73, 0xbc, 0x82, 0x92, 0x5d, 0x82, 0xf7, 0xe6, 0xf1, 0xb3, 0x78, 0xdf, 0xc3, 0x23,
	0x5d, 0x4e, 0x7b, 0x10, 0x71, 0x92, 0x44, 0x8a, 0xc5, 0x96, 0x6c, 0xe5, 0x29, 0x6c, 0xcb, 0xbf,
	0x8f, 0x99, 0xeb, 0xe3, 0xa9, 0x9c, 0xdd, 0x09, 0x19, 0xa5, 0xb1, 0x29, 0xfa, 0xe2, 0x69, 0xba,
	0x5d, 0x86, 0xa7, 0x73, 0xb5, 0xb2, 0x64, 0xce, 0x60, 0xb7, 0xcd, 0x7a, 0xdf, 0x26, 0x21, 0xe2,
	0xd9, 0x0e, 0x2e, 0xce, 0x43, 0x20, 0x7a, 0x7b, 0xd7, 0x35, 0xa2, 0x4c, 0xdb, 0x02, 0x73, 0x3a,
	0x4e, 0xa6, 0xf1, 0x5b, 0x6e, 0x02, 0x94, 0xfa, 0x17, 0x1c, 0x71, 0xc2, 0x38, 0x09, 0x96, 0x15,
	0x6d, 0xc0, 0x66, 0x72, 0xfc, 0x69, 0x4d, 0x2b, 0xc9, 0xb3, 0xf4, 0xd5, 0x3f, 0xab, 0xe9, 0xe1,
	0x91, 0x67, 0x63, 0x17, 0x36, 0x92, 0xcf, 0x6b, 0x7a, 0x6a, 0xc4, 0x51, 0x7a, 0x8e, 0x6b, 0x72,
	0xf7, 0x85, 0xe7, 0x58, 0x79, 0xea, 0x27, 0x72, 0xe1, 0x85, 0xa7, 0x7e, 0x62, 0x14, 0x61, 0x3d,
	0x39, 0x35, 0xef, 0x49, 0xc7, 0x7a, 0x72, 0x2a, 0xed, 0xba, 0x5c, 0x44, 0x61, 0xd7, 0x6d, 0x1b,
	0x2a, 0x8b, 0x72, 0x1e, 0x17, 0x76, 0xf4, 0xcf, 0x16, 0x6c, 0xb4, 0x59, 0xcf, 0x78, 0x09, 0x85,
	0xb7, 0xdb, 0x53, 0x99, 0xd7, 0x9b, 0xc9, 0xf9, 0xb5, 0xaa, 0xff, 0xc5, 0x18, 0x0b, 0x18, 0x29,
	0x18, 0x73, 0xe6, 0xe4, 0xd9, 0x92, 0xfb, 0x77, 0xa9, 0x56, 0x7d, 0x65, 0x6a, 0xa6, 0x19, 0xc1,
	0xee, 0xcc, 0x7b, 0xf1, 0xd1, 0x82, 0x30, 0xd3, 0x44, 0xcb, 0x5d, 0x91, 0x98, 0xa9, 0x75, 0xa1,
	0x38, 0xb5, 0xc0, 0x07, 0x0b, 0x42, 0xdc, 0xa5, 0x59, 0x87, 0x2b, 0xd1, 0x32, 0x1d, 0x0a, 0x0f,
	0x67, 0x37, 0x78, 0x51, 0x23, 0x66, 0x98, 0x56, 0x6d, 0x55, 0x66, 0x26, 0x18, 0xc0, 0x83, 0xbb,
	0x5b, 0xf5, 0xc1, 0x82, 0x10, 0x77, 0x58, 0xd6, 0xc7, 0xab, 0xb0, 0x32, 0x91, 0x1f, 0xe1, 0xd1,
	0xfc, 0xad, 0x5a, 0x1e, 0x66, 0x8a, 0x6d, 0x9d, 0xfc, 0x1f, 0xf6, 0x58, 0xbc, 0xf1, 0xe2, 0xf5,
	0xa8, 0x94, 0x7b, 0x33, 0x2a, 0xe5, 0xfe, 0x1a, 0x95, 0x72, 0x3f, 0xdf, 0x96, 0xd6, 0xde, 0xdc,
	0x96, 0xd6, 0x7e, 0xbf, 0x2d, 0xad, 0x7d, 0xf7, 0xc9, 0xe4, 0x9b, 0xa0, 0x23, 0x77, 0xe9, 0x20,
	0x0e, 0x11, 0x27, 0x34, 0xce, 0x5c, 0xee, 0xcd, 0xf8, 0xeb, 0x45, 0x3e, 0x13, 0x9d, 0x6d, 0xf9,
	0xd1, 0x72, 0xfc, 0x6f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x4a, 0x3e, 0x1f, 0xb3, 0xae, 0x09, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	FeedPrice(ctx context.Context, in *MsgFeedPrice, opts ...grpc.CallOption) (*MsgFeedPriceResponse, error)
	FeedMultiplePrices(ctx context.Context, in *MsgFeedMultiplePrices, opts ...grpc.CallOption) (*MsgFeedMultiplePricesResponse, error)
	RequestBandPrice(ctx context.Context, in *MsgRequestBandPrice, opts ...grpc.CallOption) (*MsgRequestBandPriceResponse, error)
	SetPriceFeeder(ctx context.Context, in *MsgSetPriceFeeder, opts ...grpc.CallOption) (*MsgSetPriceFeederResponse, error)
	DeletePriceFeeder(ctx context.Context, in *MsgDeletePriceFeeder, opts ...grpc.CallOption) (*MsgDeletePriceFeederResponse, error)
	UpdateChannel(ctx context.Context, in *MsgUpdateChannel, opts ...grpc.CallOption) (*MsgUpdateChannelResponse, error)
	UpdatePriceStatistics(ctx context.Context, in *MsgUpdatePriceStatistics, opts ...grpc.CallOption) (*MsgUpdatePriceStatisticsResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) FeedPrice(ctx context.Context, in *MsgFeedPrice, opts ...grpc.CallOption) (*MsgFeedPriceResponse, error) {
	out := new(MsgFeedPriceResponse)
	err := c.cc.Invoke(ctx, "/cascadia.oracle.v1.Msg/FeedPrice", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) FeedMultiplePrices(ctx context.Context, in *MsgFeedMultiplePrices, opts ...grpc.CallOption) (*MsgFeedMultiplePricesResponse, error) {
	out := new(MsgFeedMultiplePricesResponse)
	err := c.cc.Invoke(ctx, "/cascadia.oracle.v1.Msg/FeedMultiplePrices", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) RequestBandPrice(ctx context.Context, in *MsgRequestBandPrice, opts ...grpc.CallOption) (*MsgRequestBandPriceResponse, error) {
	out := new(MsgRequestBandPriceResponse)
	err := c.cc.Invoke(ctx, "/cascadia.oracle.v1.Msg/RequestBandPrice", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) SetPriceFeeder(ctx context.Context, in *MsgSetPriceFeeder, opts ...grpc.CallOption) (*MsgSetPriceFeederResponse, error) {
	out := new(MsgSetPriceFeederResponse)
	err := c.cc.Invoke(ctx, "/cascadia.oracle.v1.Msg/SetPriceFeeder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) DeletePriceFeeder(ctx context.Context, in *MsgDeletePriceFeeder, opts ...grpc.CallOption) (*MsgDeletePriceFeederResponse, error) {
	out := new(MsgDeletePriceFeederResponse)
	err := c.cc.Invoke(ctx, "/cascadia.oracle.v1.Msg/DeletePriceFeeder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) UpdateChannel(ctx context.Context, in *MsgUpdateChannel, opts ...grpc.CallOption) (*MsgUpdateChannelResponse, error) {
	out := new(MsgUpdateChannelResponse)
	err := c.cc.Invoke(ctx, "/cascadia.oracle.v1.Msg/UpdateChannel", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) UpdatePriceStatistics(ctx context.Context, in *MsgUpdatePriceStatistics, opts ...grpc.CallOption) (*MsgUpdatePriceStatisticsResponse, error) {
	out := new(MsgUpdatePriceStatisticsResponse)
	err := c.cc.Invoke(ctx, "/cascadia.oracle.v1.Msg/UpdatePriceStatistics", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	FeedPrice(context.Context, *MsgFeedPrice) (*MsgFeedPriceResponse, error)
	FeedMultiplePrices(context.Context, *MsgFeedMultiplePrices) (*MsgFeedMultiplePricesResponse, error)
	RequestBandPrice(context.Context, *MsgRequestBandPrice) (*MsgRequestBandPriceResponse, error)
	SetPriceFeeder(context.Context, *MsgSetPriceFeeder) (*MsgSetPriceFeederResponse, error)
	DeletePriceFeeder(context.Context, *MsgDeletePriceFeeder) (*MsgDeletePriceFeederResponse, error)
	UpdateChannel(context.Context, *MsgUpdateChannel) (*MsgUpdateChannelResponse, error)
	UpdatePriceStatistics(context.Context, *MsgUpdatePriceStatistics) (*MsgUpdatePriceStatisticsResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) FeedPrice(ctx context.Context, req *MsgFeedPrice) (*MsgFeedPriceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FeedPrice not implemented")
}
func (*UnimplementedMsgServer) FeedMultiplePrices(ctx context.Context, req *MsgFeedMultiplePrices) (*MsgFeedMultiplePricesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FeedMultiplePrices not implemented")
}
func (*UnimplementedMsgServer) RequestBandPrice(ctx context.Context, req *MsgRequestBandPrice) (*MsgRequestBandPriceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RequestBandPrice not implemented")
}
func (*UnimplementedMsgServer) SetPriceFeeder(ctx context.Context, req *MsgSetPriceFeeder) (*MsgSetPriceFeederResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetPriceFeeder not implemented")
}
func (*UnimplementedMsgServer) DeletePriceFeeder(ctx context.Context, req *MsgDeletePriceFeeder) (*MsgDeletePriceFeederResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeletePriceFeeder not implemented")
}
func (*UnimplementedMsgServer) UpdateChannel(ctx context.Context, req *MsgUpdateChannel) (*MsgUpdateChannelResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateChannel not implemented")
}
func (*UnimplementedMsgServer) UpdatePriceStatistics(ctx context.Context, req *MsgUpdatePriceStatistics) (*MsgUpdatePriceStatisticsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdatePriceStatistics not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_FeedPrice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgFeedPrice)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).FeedPrice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cascadia.oracle.v1.Msg/FeedPrice",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).FeedPrice(ctx, req.(*MsgFeedPrice))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_FeedMultiplePrices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgFeedMultiplePrices)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).FeedMultiplePrices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cascadia.oracle.v1.Msg/FeedMultiplePrices",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).FeedMultiplePrices(ctx, req.(*MsgFeedMultiplePrices))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_RequestBandPrice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgRequestBandPrice)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).RequestBandPrice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cascadia.oracle.v1.Msg/RequestBandPrice",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).RequestBandPrice(ctx, req.(*MsgRequestBandPrice))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_SetPriceFeeder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgSetPriceFeeder)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).SetPriceFeeder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cascadia.oracle.v1.Msg/SetPriceFeeder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).SetPriceFeeder(ctx, req.(*MsgSetPriceFeeder))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_DeletePriceFeeder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgDeletePriceFeeder)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).DeletePriceFeeder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cascadia.oracle.v1.Msg/DeletePriceFeeder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).DeletePriceFeeder(ctx, req.(*MsgDeletePriceFeeder))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_UpdateChannel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgUpdateChannel)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).UpdateChannel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cascadia.oracle.v1.Msg/UpdateChannel",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).UpdateChannel(ctx, req.(*MsgUpdateChannel))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_UpdatePriceStatistics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgUpdatePriceStatistics)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).UpdatePriceStatistics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cascadia.oracle.v1.Msg/UpdatePriceStatistics",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).UpdatePriceStatistics(ctx, req.(*MsgUpdatePriceStatistics))
	}
	return interceptor(ctx, in, info, handler)
}

var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "cascadia.oracle.v1.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FeedPrice",
			Handler:    _Msg_FeedPrice_Handler,
		},
		{
			MethodName: "FeedMultiplePrices",
			Handler:    _Msg_FeedMultiplePrices_Handler,
		},
		{
			MethodName: "RequestBandPrice",
			Handler:    _Msg_RequestBandPrice_Handler,
		},
		{
			MethodName: "SetPriceFeeder",
			Handler:    _Msg_SetPriceFeeder_Handler,
		},
		{
			MethodName: "DeletePriceFeeder",
			Handler:    _Msg_DeletePriceFeeder_Handler,
		},
		{
			MethodName: "UpdateChannel",
			Handler:    _Msg_UpdateChannel_Handler,
		},
		{
			MethodName: "UpdatePriceStatistics",
			Handler:    _Msg_UpdatePriceStatistics_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cascadia/oracle/v1/tx.proto",
}

func (m *MsgRequestBandPrice) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgRequestBandPrice) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgRequestBandPrice) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.ClientID) > 0 {
		i -= len(m.ClientID)
		copy(dAtA[i:], m.ClientID)
		i = encodeVarintTx(dAtA, i, uint64(len(m.ClientID)))
		i--
		dAtA[i] = 0x52
	}
	if m.ExecuteGas != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.ExecuteGas))
		i--
		dAtA[i] = 0x48
	}
	if m.PrepareGas != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.PrepareGas))
		i--
		dAtA[i] = 0x40
	}
	if len(m.FeeLimit) > 0 {
		for iNdEx := len(m.FeeLimit) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.FeeLimit[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintTx(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x3a
		}
	}
	if m.MinCount != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.MinCount))
		i--
		dAtA[i] = 0x30
	}
	if m.AskCount != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.AskCount))
		i--
		dAtA[i] = 0x28
	}
	if m.Calldata != nil {
		{
			size, err := m.Calldata.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintTx(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x22
	}
	if len(m.SourceChannel) > 0 {
		i -= len(m.SourceChannel)
		copy(dAtA[i:], m.SourceChannel)
		i = encodeVarintTx(dAtA, i, uint64(len(m.SourceChannel)))
		i--
		dAtA[i] = 0x1a
	}
	if m.OracleScriptID != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.OracleScriptID))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgRequestBandPriceResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgRequestBandPriceResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgRequestBandPriceResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgFeedPrice) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgFeedPrice) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgFeedPrice) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Provider) > 0 {
		i -= len(m.Provider)
		copy(dAtA[i:], m.Provider)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Provider)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Source) > 0 {
		i -= len(m.Source)
		copy(dAtA[i:], m.Source)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Source)))
		i--
		dAtA[i] = 0x1a
	}
	{
		size := m.Price.Size()
		i -= size
		if _, err := m.Price.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintTx(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if len(m.Asset) > 0 {
		i -= len(m.Asset)
		copy(dAtA[i:], m.Asset)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Asset)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgFeedPriceResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgFeedPriceResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgFeedPriceResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgSetPriceFeeder) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgSetPriceFeeder) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgSetPriceFeeder) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.IsActive {
		i--
		if m.IsActive {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x10
	}
	if len(m.Feeder) > 0 {
		i -= len(m.Feeder)
		copy(dAtA[i:], m.Feeder)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Feeder)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgSetPriceFeederResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgSetPriceFeederResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgSetPriceFeederResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgDeletePriceFeeder) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgDeletePriceFeeder) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgDeletePriceFeeder) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Feeder) > 0 {
		i -= len(m.Feeder)
		copy(dAtA[i:], m.Feeder)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Feeder)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgDeletePriceFeederResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgDeletePriceFeederResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgDeletePriceFeederResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgFeedMultiplePrices) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgFeedMultiplePrices) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgFeedMultiplePrices) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Prices) > 0 {
		for iNdEx := len(m.Prices) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Prices[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintTx(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgFeedMultiplePricesResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgFeedMultiplePricesResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgFeedMultiplePricesResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgUpdateChannel) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdateChannel) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdateChannel) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Channel) > 0 {
		i -= len(m.Channel)
		copy(dAtA[i:], m.Channel)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Channel)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgUpdateChannelResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdateChannelResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdateChannelResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgUpdatePriceStatistics) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdatePriceStatistics) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdatePriceStatistics) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.P1) > 0 {
		i -= len(m.P1)
		copy(dAtA[i:], m.P1)
		i = encodeVarintTx(dAtA, i, uint64(len(m.P1)))
		i--
		dAtA[i] = 0x42
	}
	if len(m.P7) > 0 {
		i -= len(m.P7)
		copy(dAtA[i:], m.P7)
		i = encodeVarintTx(dAtA, i, uint64(len(m.P7)))
		i--
		dAtA[i] = 0x3a
	}
	if len(m.P14) > 0 {
		i -= len(m.P14)
		copy(dAtA[i:], m.P14)
		i = encodeVarintTx(dAtA, i, uint64(len(m.P14)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.P30) > 0 {
		i -= len(m.P30)
		copy(dAtA[i:], m.P30)
		i = encodeVarintTx(dAtA, i, uint64(len(m.P30)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.P90) > 0 {
		i -= len(m.P90)
		copy(dAtA[i:], m.P90)
		i = encodeVarintTx(dAtA, i, uint64(len(m.P90)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.P180) > 0 {
		i -= len(m.P180)
		copy(dAtA[i:], m.P180)
		i = encodeVarintTx(dAtA, i, uint64(len(m.P180)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.P360) > 0 {
		i -= len(m.P360)
		copy(dAtA[i:], m.P360)
		i = encodeVarintTx(dAtA, i, uint64(len(m.P360)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgUpdatePriceStatisticsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdatePriceStatisticsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdatePriceStatisticsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgRequestBandPrice) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.OracleScriptID != 0 {
		n += 1 + sovTx(uint64(m.OracleScriptID))
	}
	l = len(m.SourceChannel)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.Calldata != nil {
		l = m.Calldata.Size()
		n += 1 + l + sovTx(uint64(l))
	}
	if m.AskCount != 0 {
		n += 1 + sovTx(uint64(m.AskCount))
	}
	if m.MinCount != 0 {
		n += 1 + sovTx(uint64(m.MinCount))
	}
	if len(m.FeeLimit) > 0 {
		for _, e := range m.FeeLimit {
			l = e.Size()
			n += 1 + l + sovTx(uint64(l))
		}
	}
	if m.PrepareGas != 0 {
		n += 1 + sovTx(uint64(m.PrepareGas))
	}
	if m.ExecuteGas != 0 {
		n += 1 + sovTx(uint64(m.ExecuteGas))
	}
	l = len(m.ClientID)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgRequestBandPriceResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgFeedPrice) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Asset)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = m.Price.Size()
	n += 1 + l + sovTx(uint64(l))
	l = len(m.Source)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Provider)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgFeedPriceResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgSetPriceFeeder) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Feeder)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.IsActive {
		n += 2
	}
	return n
}

func (m *MsgSetPriceFeederResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgDeletePriceFeeder) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Feeder)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgDeletePriceFeederResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgFeedMultiplePrices) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if len(m.Prices) > 0 {
		for _, e := range m.Prices {
			l = e.Size()
			n += 1 + l + sovTx(uint64(l))
		}
	}
	return n
}

func (m *MsgFeedMultiplePricesResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgUpdateChannel) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Channel)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgUpdateChannelResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgUpdatePriceStatistics) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.P360)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.P180)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.P90)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.P30)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.P14)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.P7)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.P1)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgUpdatePriceStatisticsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgRequestBandPrice) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgRequestBandPrice: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgRequestBandPrice: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field OracleScriptID", wireType)
			}
			m.OracleScriptID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.OracleScriptID |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SourceChannel", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SourceChannel = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Calldata", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Calldata == nil {
				m.Calldata = &BandPriceCallData{}
			}
			if err := m.Calldata.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AskCount", wireType)
			}
			m.AskCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.AskCount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MinCount", wireType)
			}
			m.MinCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MinCount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FeeLimit", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.FeeLimit = append(m.FeeLimit, types.Coin{})
			if err := m.FeeLimit[len(m.FeeLimit)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PrepareGas", wireType)
			}
			m.PrepareGas = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PrepareGas |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ExecuteGas", wireType)
			}
			m.ExecuteGas = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ExecuteGas |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ClientID", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ClientID = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgRequestBandPriceResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgRequestBandPriceResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgRequestBandPriceResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgFeedPrice) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgFeedPrice: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgFeedPrice: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Asset", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Asset = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Price", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Price.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Source", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Source = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Provider", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Provider = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgFeedPriceResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgFeedPriceResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgFeedPriceResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgSetPriceFeeder) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgSetPriceFeeder: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgSetPriceFeeder: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Feeder", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Feeder = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field IsActive", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.IsActive = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgSetPriceFeederResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgSetPriceFeederResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgSetPriceFeederResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgDeletePriceFeeder) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgDeletePriceFeeder: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgDeletePriceFeeder: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Feeder", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Feeder = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgDeletePriceFeederResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgDeletePriceFeederResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgDeletePriceFeederResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgFeedMultiplePrices) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgFeedMultiplePrices: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgFeedMultiplePrices: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Prices", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Prices = append(m.Prices, Price{})
			if err := m.Prices[len(m.Prices)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgFeedMultiplePricesResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgFeedMultiplePricesResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgFeedMultiplePricesResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgUpdateChannel) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdateChannel: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdateChannel: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Channel", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Channel = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgUpdateChannelResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdateChannelResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdateChannelResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgUpdatePriceStatistics) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdatePriceStatistics: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdatePriceStatistics: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field P360", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.P360 = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field P180", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.P180 = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field P90", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.P90 = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field P30", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.P30 = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field P14", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.P14 = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field P7", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.P7 = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field P1", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.P1 = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgUpdatePriceStatisticsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdatePriceStatisticsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdatePriceStatisticsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
