// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: cascadia/penalty/v1/tx.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type MsgUpdatePenaltyAccountRequest struct {
	Creator    string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	NewAddress string `protobuf:"bytes,2,opt,name=new_address,json=newAddress,proto3" json:"new_address,omitempty"`
}

func (m *MsgUpdatePenaltyAccountRequest) Reset()         { *m = MsgUpdatePenaltyAccountRequest{} }
func (m *MsgUpdatePenaltyAccountRequest) String() string { return proto.CompactTextString(m) }
func (*MsgUpdatePenaltyAccountRequest) ProtoMessage()    {}
func (*MsgUpdatePenaltyAccountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6f41382fb7c6dd14, []int{0}
}
func (m *MsgUpdatePenaltyAccountRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdatePenaltyAccountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdatePenaltyAccountRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdatePenaltyAccountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdatePenaltyAccountRequest.Merge(m, src)
}
func (m *MsgUpdatePenaltyAccountRequest) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdatePenaltyAccountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdatePenaltyAccountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdatePenaltyAccountRequest proto.InternalMessageInfo

func (m *MsgUpdatePenaltyAccountRequest) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgUpdatePenaltyAccountRequest) GetNewAddress() string {
	if m != nil {
		return m.NewAddress
	}
	return ""
}

type MsgUpdatePenaltyAccountResponse struct {
	OldAddress string `protobuf:"bytes,1,opt,name=old_address,json=oldAddress,proto3" json:"old_address,omitempty"`
}

func (m *MsgUpdatePenaltyAccountResponse) Reset()         { *m = MsgUpdatePenaltyAccountResponse{} }
func (m *MsgUpdatePenaltyAccountResponse) String() string { return proto.CompactTextString(m) }
func (*MsgUpdatePenaltyAccountResponse) ProtoMessage()    {}
func (*MsgUpdatePenaltyAccountResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6f41382fb7c6dd14, []int{1}
}
func (m *MsgUpdatePenaltyAccountResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdatePenaltyAccountResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdatePenaltyAccountResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdatePenaltyAccountResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdatePenaltyAccountResponse.Merge(m, src)
}
func (m *MsgUpdatePenaltyAccountResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdatePenaltyAccountResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdatePenaltyAccountResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdatePenaltyAccountResponse proto.InternalMessageInfo

func (m *MsgUpdatePenaltyAccountResponse) GetOldAddress() string {
	if m != nil {
		return m.OldAddress
	}
	return ""
}

func init() {
	proto.RegisterType((*MsgUpdatePenaltyAccountRequest)(nil), "cascadia.penalty.v1.MsgUpdatePenaltyAccountRequest")
	proto.RegisterType((*MsgUpdatePenaltyAccountResponse)(nil), "cascadia.penalty.v1.MsgUpdatePenaltyAccountResponse")
}

func init() { proto.RegisterFile("cascadia/penalty/v1/tx.proto", fileDescriptor_6f41382fb7c6dd14) }

var fileDescriptor_6f41382fb7c6dd14 = []byte{
	// 312 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x92, 0x3f, 0x4b, 0x03, 0x31,
	0x18, 0xc6, 0x1b, 0x05, 0xc5, 0xb8, 0x9d, 0x1d, 0x6a, 0x91, 0x28, 0x9d, 0x5c, 0x4c, 0x68, 0x2b,
	0x82, 0x63, 0xbb, 0x17, 0x4a, 0xc5, 0x45, 0x84, 0x92, 0x26, 0x31, 0x1e, 0xb4, 0x79, 0xcf, 0x4b,
	0xae, 0x7f, 0x46, 0x47, 0x27, 0xfd, 0x30, 0x7e, 0x08, 0xc7, 0xe2, 0xe4, 0x28, 0x77, 0x5f, 0x44,
	0xda, 0xdc, 0xdd, 0x54, 0x2d, 0x6e, 0xc9, 0xf3, 0x3c, 0xef, 0x2f, 0x6f, 0xde, 0x04, 0x9f, 0x08,
	0x6e, 0x05, 0x97, 0x21, 0x67, 0x91, 0x32, 0x7c, 0xec, 0x16, 0x6c, 0xda, 0x64, 0x6e, 0x4e, 0xa3,
	0x18, 0x1c, 0x04, 0x47, 0x85, 0x4b, 0x73, 0x97, 0x4e, 0x9b, 0xf5, 0x63, 0x01, 0x76, 0x02, 0x76,
	0xb8, 0x8e, 0x30, 0xbf, 0xf1, 0xf9, 0x7a, 0x55, 0x83, 0x06, 0xaf, 0xaf, 0x56, 0x5e, 0x6d, 0xbc,
	0x22, 0x4c, 0x7a, 0x56, 0xdf, 0x46, 0x92, 0x3b, 0xd5, 0xf7, 0xa0, 0x8e, 0x10, 0x90, 0x18, 0x37,
	0x50, 0x4f, 0x89, 0xb2, 0x2e, 0x68, 0xe1, 0x7d, 0x11, 0x2b, 0xee, 0x20, 0xae, 0xa1, 0x33, 0x74,
	0x7e, 0xd0, 0xad, 0x7d, 0xbe, 0x5f, 0x54, 0x73, 0x76, 0x47, 0xca, 0x58, 0x59, 0x7b, 0xe3, 0xe2,
	0xd0, 0xe8, 0x41, 0x11, 0x0c, 0xae, 0xf1, 0xa1, 0x51, 0xb3, 0x21, 0xf7, 0x6e, 0x6d, 0x67, 0x4b,
	0x1d, 0x36, 0x6a, 0x96, 0x2b, 0x8d, 0x7b, 0x7c, 0xfa, 0x6b, 0x43, 0x36, 0x02, 0x63, 0xd5, 0x8a,
	0x0e, 0x63, 0x59, 0xd2, 0xb7, 0x75, 0x85, 0x61, 0x2c, 0x73, 0xa5, 0xf5, 0x82, 0xf0, 0x6e, 0xcf,
	0xea, 0xe0, 0x19, 0xe1, 0xea, 0xa6, 0x33, 0x82, 0x36, 0xdd, 0x30, 0x57, 0xfa, 0xf7, 0x88, 0xea,
	0x97, 0xff, 0x2b, 0xf2, 0xd7, 0xe8, 0xf6, 0x3f, 0x52, 0x82, 0x96, 0x29, 0x41, 0xdf, 0x29, 0x41,
	0x6f, 0x19, 0xa9, 0x2c, 0x33, 0x52, 0xf9, 0xca, 0x48, 0xe5, 0xee, 0x4a, 0x87, 0xee, 0x31, 0x19,
	0x51, 0x01, 0x13, 0x56, 0x90, 0x1f, 0x20, 0x31, 0x92, 0xbb, 0x10, 0x4c, 0x29, 0xb1, 0x79, 0xf9,
	0x33, 0xdc, 0x22, 0x52, 0x76, 0xb4, 0xb7, 0x7e, 0xd4, 0xf6, 0x4f, 0x00, 0x00, 0x00, 0xff, 0xff,
	0xfd, 0x4e, 0x2c, 0x8e, 0x3a, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	UpdatePenaltyAccount(ctx context.Context, in *MsgUpdatePenaltyAccountRequest, opts ...grpc.CallOption) (*MsgUpdatePenaltyAccountResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) UpdatePenaltyAccount(ctx context.Context, in *MsgUpdatePenaltyAccountRequest, opts ...grpc.CallOption) (*MsgUpdatePenaltyAccountResponse, error) {
	out := new(MsgUpdatePenaltyAccountResponse)
	err := c.cc.Invoke(ctx, "/cascadia.penalty.v1.Msg/UpdatePenaltyAccount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	UpdatePenaltyAccount(context.Context, *MsgUpdatePenaltyAccountRequest) (*MsgUpdatePenaltyAccountResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) UpdatePenaltyAccount(ctx context.Context, req *MsgUpdatePenaltyAccountRequest) (*MsgUpdatePenaltyAccountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdatePenaltyAccount not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_UpdatePenaltyAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgUpdatePenaltyAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).UpdatePenaltyAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cascadia.penalty.v1.Msg/UpdatePenaltyAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).UpdatePenaltyAccount(ctx, req.(*MsgUpdatePenaltyAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "cascadia.penalty.v1.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpdatePenaltyAccount",
			Handler:    _Msg_UpdatePenaltyAccount_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cascadia/penalty/v1/tx.proto",
}

func (m *MsgUpdatePenaltyAccountRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdatePenaltyAccountRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdatePenaltyAccountRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.NewAddress) > 0 {
		i -= len(m.NewAddress)
		copy(dAtA[i:], m.NewAddress)
		i = encodeVarintTx(dAtA, i, uint64(len(m.NewAddress)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgUpdatePenaltyAccountResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdatePenaltyAccountResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdatePenaltyAccountResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.OldAddress) > 0 {
		i -= len(m.OldAddress)
		copy(dAtA[i:], m.OldAddress)
		i = encodeVarintTx(dAtA, i, uint64(len(m.OldAddress)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgUpdatePenaltyAccountRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.NewAddress)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgUpdatePenaltyAccountResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.OldAddress)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgUpdatePenaltyAccountRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdatePenaltyAccountRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdatePenaltyAccountRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NewAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.NewAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgUpdatePenaltyAccountResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdatePenaltyAccountResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdatePenaltyAccountResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OldAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.OldAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
